
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
environment: prod
baseurl: https://sunyunlee.github.io
url: https://sunyunlee.github.io
plugins:
  - jekyll-scholar
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-katex
kramdown:
  math_engine: mathjax
markdown: kramdown
usemathjax: true
katex:
